package com.OnlineMarketplace.OnlineMarketplace.Wordlist;

import java.util.Arrays;
import java.util.List;

public class Wordlist {

    public static List<String> productTitles = Arrays.asList("Wireless Noise-Canceling Headphones", "Smart LED Desk Lamp with USB Charging", "Ergonomic Office Chair with Lumbar Support", "Portable Solar Power Bank 20,000mAh",
            "Smartwatch with Heart Rate Monitor", "4K Ultra HD Streaming Media Player", "Bluetooth Sleep Mask with Built-in Speakers", "Adjustable Standing Desk Converter",
            "Multi-Device Wireless Keyboard and Mouse", "Self-Cleaning Water Bottle with UV Light", "Touchscreen Smart Refrigerator", "Cordless Handheld Vacuum Cleaner",
            "Smart Digital Picture Frame with Wi-Fi", "Noise-Isolating Wireless Earbuds", "Rechargeable Electric Toothbrush with Timer", "Home Security Camera with Night Vision",
            "Outdoor Solar-Powered LED String Lights", "Compact Espresso Machine with Milk Frother", "AI-Powered Robot Vacuum and Mop", "Wireless Charging Pad for Multiple Devices",
            "Smart Air Purifier with HEPA Filter", "Portable Mini Projector with Wi-Fi", "Electric Heated Blanket with Timer", "Smart Lock with Fingerprint Recognition",
            "Adjustable Dumbbells for Home Workouts", "Waterproof Bluetooth Shower Speaker", "Smart Thermostat with Remote Control", "Foldable Laptop Stand with Cooling Fan",
            "Smart Light Bulbs with Color Changing Features", "Ergonomic Memory Foam Pillow", "All-in-One Printer with Wireless Connectivity", "Compact Air Fryer for Healthy Cooking",
            "Multi-Functional Vegetable Chopper", "Electric Standing Desk with Height Memory", "Wearable Posture Corrector", "Automatic Soap Dispenser with Sensor",
            "Stainless Steel Insulated Travel Mug", "Multi-Port USB Charging Station", "Cordless Hair Clippers for Men", "Smart Home Hub with Voice Control",
            "Portable Bluetooth Speaker with Deep Bass", "Collapsible Water Bottle for Travel", "HD Webcam with Microphone", "Noise-Canceling Sleep Headphones",
            "Reusable Notebook with Cloud Sync", "Electric Foot Massager with Heat", "Automatic Pet Feeder with App Control", "Water-Resistant Laptop Backpack with USB Port",
            "UV Phone Sanitizer and Charger", "Wireless Meat Thermometer for Grilling", "Mini Fridge with Freezer", "Smart Scale with Body Composition Analysis",
            "Fitness Tracker with Blood Oxygen Monitor", "DIY 3D Printer Kit", "Cordless Electric Kettle with Temperature Control", "Solar-Powered Outdoor Security Camera",
            "Smart Ceiling Fan with Remote and App Control", "Portable Handheld Fan with Rechargeable Battery", "Smart Mirror with Touchscreen Display", "Motion Sensor LED Closet Lights",
            "Smart Garage Door Opener with Wi-Fi", "Robot Lawn Mower with App Control", "Convertible Sofa Bed with Storage", "Adjustable Tablet Stand for Bed",
            "Noise-Reducing Sleep Earplugs", "Compact Travel Steamer for Clothes", "USB-C Hub with Multiple Ports", "Wearable Sleep Tracker Ring",
            "Personalized LED Name Sign", "Handheld Deep Tissue Massage Gun", "Smart Bike Helmet with LED Turn Signals", "Rechargeable Camping Lantern with Power Bank",
            "Floating Pool Speaker with LED Lights", "Magnetic Car Phone Mount", "Adjustable Laptop Cooling Pad", "Portable Water Flosser for Oral Care",
            "Smart Diffuser with Essential Oil Blends", "Memory Foam Seat Cushion for Office Chairs", "Electric Spin Scrubber for Bathroom Cleaning", "Bamboo Charging Station for Multiple Devices",
            "Collapsible Silicone Food Storage Containers", "Smart Jump Rope with Digital Counter", "Compact Electric Rice Cooker", "Portable Projector Screen",
            "Multi-Compartment Meal Prep Lunch Box", "High-Pressure Shower Head with Filter", "Wireless Charging Car Mount", "Retro Bluetooth Record Player",
            "Smart UV Light Toothbrush Sanitizer", "Heated Gloves for Winter Sports", "Electric Milk Frother for Lattes and Cappuccinos", "Solar-Powered Garden Fountain",
            "Rechargeable Motion Sensor Night Light", "Magnetic Wireless Power Bank", "Foldable Bluetooth Keyboard", "Dual Monitor Adjustable Desk Mount",
            "Infrared Thermometer for Cooking and BBQ", "Smart Plug with Energy Monitoring", "Voice-Controlled Smart Trash Can", "Ergonomic Footrest for Under Desk",
            "Waterproof Action Camera with 4K Resolution", "Auto-Sensor LED Night Light", "Convertible Baby Stroller with Car Seat", "Pet GPS Tracker with Real-Time Monitoring");

    public static List<String> productDescriptions = Arrays.asList("Experience immersive sound with Wireless Noise-Canceling Headphones, featuring advanced ANC technology and up to 40 hours of battery life.",
            "Smart LED Desk Lamp with USB Charging offers adjustable brightness, color temperature, and a built-in USB port for convenient charging.",
            "Ergonomic Office Chair with Lumbar Support provides all-day comfort with breathable mesh, adjustable armrests, and a reclining backrest.",
            "Portable Solar Power Bank 20,000mAh keeps your devices charged with dual USB ports and solar panel recharging for outdoor adventures.",
            "Smartwatch with Heart Rate Monitor tracks fitness, sleep, and notifications with an always-on display and long battery life.",
            "4K Ultra HD Streaming Media Player delivers stunning visuals, Dolby Atmos sound, and access to thousands of apps and streaming services.",
            "Bluetooth Sleep Mask with Built-in Speakers blocks out light while playing soothing sounds or music for a restful night’s sleep.",
            "Adjustable Standing Desk Converter allows you to switch between sitting and standing effortlessly with a spacious work surface.",
            "Multi-Device Wireless Keyboard and Mouse connect seamlessly to multiple devices via Bluetooth, enhancing productivity and convenience.",
            "Self-Cleaning Water Bottle with UV Light eliminates bacteria and odors, keeping your drinks fresh and safe with one-touch sterilization.",
            "Touchscreen Smart Refrigerator with built-in Wi-Fi lets you create shopping lists, stream music, and manage food inventory easily.",
            "Cordless Handheld Vacuum Cleaner features powerful suction, a lightweight design, and multiple attachments for quick and efficient cleaning.",
            "Smart Digital Picture Frame with Wi-Fi lets you display and update photos from anywhere, making it perfect for families and gifts.",
            "Noise-Isolating Wireless Earbuds provide deep bass, clear audio, and a comfortable fit with sweat resistance and touch controls.",
            "Rechargeable Electric Toothbrush with Timer features multiple cleaning modes, a built-in timer, and sonic vibrations for superior oral care.",
            "Home Security Camera with Night Vision offers 1080p HD video, motion detection, and two-way audio for 24/7 home protection.",
            "Outdoor Solar-Powered LED String Lights enhance your backyard with energy-efficient, weather-resistant illumination for any occasion.",
            "Compact Espresso Machine with Milk Frother delivers rich, barista-quality coffee and cappuccinos with a simple one-touch operation.",
            "AI-Powered Robot Vacuum and Mop intelligently maps and cleans floors with automated scheduling and smart app control.",
            "Wireless Charging Pad for Multiple Devices powers your smartphone, smartwatch, and earbuds simultaneously with fast wireless charging.",
            "Smart Air Purifier with HEPA Filter removes allergens, dust, and odors while monitoring air quality in real time via an app.",
            "Portable Mini Projector with Wi-Fi lets you stream movies and games in HD, with built-in speakers and a compact design.",
            "Electric Heated Blanket with Timer keeps you warm with adjustable heat settings, an automatic shutoff, and ultra-soft fabric.",
            "Smart Lock with Fingerprint Recognition provides keyless entry with biometric scanning, app control, and remote access features.",
            "Adjustable Dumbbells for Home Workouts allow quick weight changes for a full-body workout without the need for multiple sets.",
            "Waterproof Bluetooth Shower Speaker delivers crystal-clear sound, strong bass, and a suction cup for easy bathroom mounting.",
            "Smart Thermostat with Remote Control optimizes energy use while letting you adjust temperature settings from anywhere via app.",
            "Foldable Laptop Stand with Cooling Fan improves posture and prevents overheating with an ergonomic design and built-in fan.",
            "Smart Light Bulbs with Color Changing Features set the mood with millions of colors, voice control, and customizable scenes.",
            "Ergonomic Memory Foam Pillow supports your neck and spine for a restful sleep with a breathable, hypoallergenic cover.",
            "All-in-One Printer with Wireless Connectivity prints, scans, and copies with high-speed performance and smartphone compatibility.",
            "Compact Air Fryer for Healthy Cooking prepares crispy meals with little to no oil, featuring preset cooking functions and a digital display.",
            "Multi-Functional Vegetable Chopper speeds up meal prep with multiple interchangeable blades for slicing, dicing, and grating.",
            "Electric Standing Desk with Height Memory adjusts smoothly with programmable presets for an ergonomic and productive workspace.",
            "Wearable Posture Corrector helps improve back alignment with adjustable straps and a discreet design for all-day use.",
            "Automatic Soap Dispenser with Sensor provides touchless operation with adjustable soap levels, preventing germ spread.",
            "Stainless Steel Insulated Travel Mug keeps drinks hot or cold for hours with a spill-proof lid and sleek, portable design.",
            "Multi-Port USB Charging Station charges multiple devices at once with fast-charging capabilities and intelligent safety features.",
            "Cordless Hair Clippers for Men provide precise haircuts with adjustable length settings, sharp blades, and a rechargeable battery.",
            "Smart Home Hub with Voice Control connects and automates smart devices, allowing hands-free operation with voice commands.",
            "Portable Bluetooth Speaker with Deep Bass delivers powerful sound, long battery life, and a waterproof design for outdoor use.",
            "Collapsible Water Bottle for Travel saves space with its foldable design, leak-proof cap, and BPA-free construction.",
            "HD Webcam with Microphone enhances video calls with high-resolution video, auto-focus, and noise-canceling mic technology.",
            "Noise-Canceling Sleep Headphones provide comfortable, all-night use with soft headband design and built-in Bluetooth speakers.",
            "Reusable Notebook with Cloud Sync allows you to digitize handwritten notes with erasable pages and a companion app.",
            "Electric Foot Massager with Heat soothes sore feet with deep kneading massage, adjustable settings, and infrared warmth.",
            "Automatic Pet Feeder with App Control schedules feedings, monitors portion sizes, and dispenses food remotely via smartphone.",
            "Water-Resistant Laptop Backpack with USB Port offers padded compartments, anti-theft features, and an external charging port.",
            "UV Phone Sanitizer and Charger eliminates bacteria while wirelessly charging your smartphone in a sleek, portable case.",
            "Wireless Meat Thermometer for Grilling provides real-time temperature monitoring via Bluetooth, ensuring perfectly cooked meats.",
            "Mini Fridge with Freezer offers compact storage for beverages and snacks with an adjustable thermostat and removable shelves.",
            "Smart Scale with Body Composition Analysis tracks weight, BMI, muscle mass, and more with seamless app integration.",
            "Fitness Tracker with Blood Oxygen Monitor measures heart rate, steps, sleep, and SpO2 levels for comprehensive health insights.",
            "DIY 3D Printer Kit lets you create custom objects with precision, featuring an easy-to-assemble design and high-resolution printing.",
            "Cordless Electric Kettle with Temperature Control heats water quickly with adjustable settings and a stylish, modern design.",
            "Solar-Powered Outdoor Security Camera provides 24/7 monitoring with motion detection, night vision, and cloud storage options.",
            "Smart Ceiling Fan with Remote and App Control offers customizable airflow, scheduling, and voice assistant compatibility.",
            "Portable Handheld Fan with Rechargeable Battery delivers powerful cooling with adjustable speeds and a compact, foldable design.",
            "Smart Mirror with Touchscreen Display integrates beauty and technology with LED lighting, calendar sync, and voice control.",
            "Motion Sensor LED Closet Lights provide automatic illumination with energy-efficient LED bulbs and wireless installation.",
            "Smart Garage Door Opener with Wi-Fi enables remote access and monitoring with a smartphone app for added security.",
            "Robot Lawn Mower with App Control autonomously trims your lawn with smart navigation and adjustable cutting heights.",
            "Convertible Sofa Bed with Storage combines comfort and functionality with a sleek design and hidden storage compartment.",
            "Adjustable Tablet Stand for Bed offers hands-free convenience with multiple angles and a sturdy, foldable design.",
            "Noise-Reducing Sleep Earplugs provide effective sound isolation for uninterrupted sleep and relaxation.",
            "Compact Travel Steamer for Clothes quickly removes wrinkles with powerful steam output and a portable, lightweight design.", "USB-C Hub with Multiple Ports expands your connectivity with high-speed data transfer, HDMI output, and multiple USB-A and USB-C ports.",
            "Wearable Sleep Tracker Ring monitors sleep patterns, heart rate, and oxygen levels with a lightweight, comfortable design and app integration.",
            "Personalized LED Name Sign creates a custom illuminated display for your home, office, or events with adjustable brightness and colors.",
            "Handheld Deep Tissue Massage Gun relieves muscle soreness with powerful percussive therapy, multiple speed settings, and interchangeable heads.",
            "Smart Bike Helmet with LED Turn Signals enhances road safety with built-in lighting, Bluetooth connectivity, and voice command compatibility.",
            "Rechargeable Camping Lantern with Power Bank provides bright LED illumination and doubles as a backup charger for your devices.",
            "Floating Pool Speaker with LED Lights delivers waterproof, high-quality sound with synchronized multicolor lighting effects.",
            "Magnetic Car Phone Mount securely holds your smartphone in place with a strong magnetic grip and a 360-degree adjustable swivel design.",
            "Adjustable Laptop Cooling Pad prevents overheating with powerful fans, an ergonomic tilt, and customizable speed settings.",
            "Portable Water Flosser for Oral Care ensures deep cleaning between teeth with adjustable water pressure and a rechargeable battery.",
            "Smart Diffuser with Essential Oil Blends creates a relaxing atmosphere with app-controlled mist levels, LED lighting, and timer settings.",
            "Memory Foam Seat Cushion for Office Chairs provides ergonomic support and pressure relief for long hours of sitting.",
            "Electric Spin Scrubber for Bathroom Cleaning makes scrubbing effortless with rotating brush heads and an extendable handle for hard-to-reach areas.",
            "Bamboo Charging Station for Multiple Devices organizes and charges multiple gadgets simultaneously with built-in cable management.",
            "Collapsible Silicone Food Storage Containers save space in your kitchen with a flexible, durable, and leak-proof design.",
            "Smart Jump Rope with Digital Counter tracks jumps, calories burned, and workout time via an integrated LCD display and app sync.",
            "Compact Electric Rice Cooker simplifies meal prep with one-touch operation, automatic keep-warm function, and a nonstick pot.",
            "Portable Projector Screen provides a smooth, high-gain surface for HD projection, perfect for home theaters and outdoor movies.",
            "Multi-Compartment Meal Prep Lunch Box keeps food fresh and organized with leak-proof compartments and microwave-safe materials.",
            "High-Pressure Shower Head with Filter enhances water flow and removes impurities for a spa-like shower experience.",
            "Wireless Charging Car Mount secures your phone while charging it wirelessly, featuring auto-clamp technology and 360-degree rotation.",
            "Retro Bluetooth Record Player combines vintage style with modern features, including built-in speakers, Bluetooth, and vinyl playback.",
            "Smart UV Light Toothbrush Sanitizer kills bacteria and germs on toothbrushes using UV-C technology, ensuring a hygienic oral care routine.",
            "Heated Gloves for Winter Sports provide warmth and comfort with adjustable heat settings and a rechargeable battery.",
            "Electric Milk Frother for Lattes and Cappuccinos creates creamy froth in seconds with multiple temperature and texture settings.",
            "Solar-Powered Garden Fountain adds elegance to outdoor spaces with a self-sustaining water feature powered by sunlight.",
            "Rechargeable Motion Sensor Night Light provides automatic illumination with energy-efficient LED technology and a compact design.",
            "Magnetic Wireless Power Bank offers cable-free charging on the go with a sleek design, strong magnet, and fast-charging capabilities.",
            "Foldable Bluetooth Keyboard enhances portability with a compact, lightweight design and seamless wireless connectivity.",
            "Dual Monitor Adjustable Desk Mount maximizes workspace efficiency with full-motion arms, height adjustment, and cable management.",
            "Infrared Thermometer for Cooking and BBQ ensures precision temperature readings for meats, liquids, and surfaces with instant results.",
            "Smart Plug with Energy Monitoring allows remote control of appliances while tracking power usage via a smartphone app.",
            "Voice-Controlled Smart Trash Can opens hands-free with motion detection or voice commands for a hygienic and modern waste disposal solution.",
            "Ergonomic Footrest for Under Desk improves posture and comfort with adjustable height, textured massage surface, and sturdy support.",
            "Waterproof Action Camera with 4K Resolution captures stunning ultra-HD video with image stabilization, slow-motion, and a rugged, waterproof build.",
            "Auto-Sensor LED Night Light brightens dark spaces automatically with motion detection and an energy-saving design.",
            "Convertible Baby Stroller with Car Seat offers versatility with a travel-friendly system that easily converts between stroller and car seat.",
            "Pet GPS Tracker with Real-Time Monitoring provides live location tracking, activity monitoring, and geofencing alerts for your pet’s safety."
    );

    public static List<Double> productPrices = Arrays.asList(129.99, 39.99, 189.99, 49.99, 99.99, 59.99, 29.99, 159.99, 79.99, 89.99,
            2199.99, 69.99, 149.99, 79.99, 49.99, 99.99, 34.99, 129.99, 299.99, 39.99,
            149.99, 199.99, 59.99, 179.99, 99.99, 24.99, 129.99, 39.99, 19.99, 59.99,
            199.99, 89.99, 29.99, 299.99, 49.99, 24.99, 19.99, 79.99, 59.99, 99.99,
            39.99, 14.99, 49.99, 69.99, 34.99, 129.99, 79.99, 99.99, 59.99, 79.99,
            99.99, 399.99, 49.99, 89.99, 129.99, 39.99, 59.99, 199.99, 149.99, 89.99,
            179.99, 249.99, 499.99, 39.99, 14.99, 49.99, 29.99, 99.99, 199.99, 79.99,
            59.99, 129.99, 89.99, 59.99, 19.99, 39.99, 199.99, 49.99, 79.99, 99.99,
            89.99, 34.99, 149.99, 79.99, 24.99, 19.99, 299.99, 99.99, 129.99, 59.99,
            79.99, 69.99, 49.99, 249.99, 99.99, 119.99, 39.99, 59.99, 199.99, 89.99, 52.99,34.55, 1.99, 5.0
    );
}
